# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Script
      run: |
        set-location QuranAnalyzer.WebUI/wwwroot/
        npm install
        npm run-script build-production
        Remove-Item 'react-with-dotnet' -Recurse
        Remove-Item 'package.json'
        Remove-Item 'package-lock.json'
        Remove-Item 'index-development.jsx'
        Remove-Item 'index.jsx'
        Remove-Item 'app.css'
      shell: pwsh

    - uses: EasyDesk/action-dotnet-publish@v1
      with:
         # (Optional) The path to the project that should be published.
         # If not specified, defaults to '.'.
         path: 'QuranAnalyzer.WebUI/'

         # (Optional) Additional command line arguments to be passed to 'dotnet test'.
         # If not specified, defaults to 'packages'.
         #output-dir: 'packages'

         # (Optional) The build configuration.
         # If not specified, defaults to 'Release'.
         #build-configuration: Release

         # (Optional) Whether to skip the build using the '--no-build' flag.
         # If not specified, defaults to true.
         skip-build: false


    - name: Script
      run: |
        Remove-Item 'packages/ReactWithDotNet.Libraries.pdb'
        Remove-Item 'packages/ReactWithDotNet.Libraries.xml'
        Remove-Item 'packages/ReactWithDotNet.pdb'
        Remove-Item 'packages/ReactWithDotNet.xml'
        Remove-Item 'packages/QuranAnalyzer.WebUI.pdb'
        Remove-Item 'packages/QuranAnalyzer.pdb'
      shell: pwsh


    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: win5173.site4now.net
        username: beyaz1404-001
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: packages/
        server-dir: 19sisteminedir/

    - uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release.zip'
        directory: 'packages/'

    - uses: djnicholson/release-action@v2.11
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        asset-name: 'release.zip'
        file: 'packages/release.zip'
